server {
    listen 80;
    listen [::]:80;
    server_name luma.193-233-126-148.sslip.io;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 308 https://lumori.ru$request_uri; }
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name luma.193-233-126-148.sslip.io;
    ssl_certificate /etc/letsencrypt/live/luma.193-233-126-148.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/luma.193-233-126-148.sslip.io/privkey.pem;
    return 308 https://lumori.ru$request_uri;
}
